### ISSUE TITLE
Use the "typePredicate" config parameter to changer rdf:type to wdt:P31, instead of doing a post-processing on the query

### ISSUE THREAD

**Issue by tfrancart** [lubianat/sparnatural_wikidata_prototype#2]
See https://docs.sparnatural.eu/Javascript-integration#parameters-reference

![image](https://user-images.githubusercontent.com/2728945/171734162-c37b4512-cd34-4192-b746-f30eb18559cd.png)

**Comment by lubianat** [comment]
@tfrancart thanks!
